import { CartItem, FilterType, Product } from './types';

export const FILTER_OPTIONS: { label: FilterType; cardType: string | null }[] = [
    { label: 'TODOS', cardType: null },
    { label: 'MONSTROS', cardType: 'MONSTER' },
    { label: 'MAGIAS', cardType: 'SPELL' },
    { label: 'ARMADILHAS', cardType: 'TRAP' },
    { label: 'TERRENOS', cardType: 'LAND' },
    { label: 'CRIATURAS', cardType: 'CREATURE' },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 1,
        name: 'The Wandering Emperor',
        description: 'Planeswalker lendária de Magic: The Gathering.',
        price: 89.9,
        image: '/images/cards/miniatures/the-wandering-emperor.jpg',
        fullImage: '/images/cards/full/the-wandering-emperor.jpg',
        game: 'mtg',
        cardType: 'CREATURE',
        rarity: 'Mythic Rare',
        stock: 4,
        badge: 'NOVO',
    },
    {
        id: 2,
        name: 'Gift of Orzhova',
        description: 'Encantamento clássico do clã Orzhov.',
        price: 12.5,
        oldPrice: 25.0,
        image: '/images/cards/miniatures/gift-of-orzhova.jpg',
        fullImage: '/images/cards/full/gift-of-orzhova.jpg',
        game: 'mtg',
        cardType: 'SPELL',
        rarity: 'Uncommon',
        stock: 15,
        badge: 'PROMO',
    },
    {
        id: 3,
        name: 'Path of Exile',
        description: 'Carta ilustrada com arte exclusiva.',
        price: 45.0,
        image: '/images/cards/miniatures/poe.jpg',
        fullImage: '/images/cards/full/poe.jpg',
        game: 'mtg',
        cardType: 'CREATURE',
        rarity: 'Rare',
        stock: 7,
    },
    {
        id: 4,
        name: 'Sword of Feast and Famine',
        description: 'Artefato poderoso de equipamento.',
        price: 120.0,
        image: '/images/cards/miniatures/sword-of-feast.jpg',
        fullImage: '/images/cards/full/sword-of-feast.jpg',
        game: 'mtg',
        cardType: 'TRAP',
        rarity: 'Mythic Rare',
        stock: 3,
    },
    {
        id: 5,
        name: 'Blue-Eyes Chaos Dragon',
        description:
            'Esta carta não pode ser invocada por invocação normal ou setada. Deve ser invocada especialmente (da sua mão) banindo 1 monstro de LUZ e 1 monstro de TREVAS do seu cemitério. Uma vez por turno: você pode escolher 1 monstro virado para cima no campo; bana esse alvo. Esta carta não pode atacar no turno em que você ativar este efeito.',
        price: 145.9,
        oldPrice: 180.0,
        image: '/images/cards/detail/blue-eyes-chaos-dragon.png',
        fullImage: '/images/cards/detail/blue-eyes-chaos-dragon.png',
        game: 'yugioh',
        cardType: 'MONSTER',
        rarity: 'Ultra Rare',
        stock: 8,
        badge: 'PROMO',
        cardSubtypes: 'DRAGON / RITUAL / EFFECT',
        edition: '1st Edition',
    },
];

export const MOCK_CART_ITEMS: CartItem[] = [
    {
        id: 1,
        name: 'Black Lotus (Proxy Art)',
        image: '/images/cards/black-lotus-proxy.png',
        price: 45.0,
        quantity: 1,
        game: 'mtg',
        category: 'Magic: The Gathering',
        details: 'Condição: NM (Near Mint) • Idioma: PT-BR',
    },
    {
        id: 2,
        name: 'Blue-Eyes White Dragon',
        image: '/images/cards/blue-eyes-white-dragon.png',
        price: 120.0,
        quantity: 1,
        game: 'yugioh',
        category: 'Yu-Gi-Oh!',
        details: 'Edição: LOB-001 • 1ª Edição',
        rarity: 'RARE',
    },
    {
        id: 3,
        name: 'Pro-Matte Sleeves (60un)',
        image: '/images/cards/sleeves-pro-matte.jpg',
        price: 25.0,
        quantity: 2,
        category: 'Acessórios',
        details: 'Cor: Preto Fosco',
    },
];

export function getProductById(id: number): Product | undefined {
    return MOCK_PRODUCTS.find((p) => p.id === id);
}

export const MOCK_RELATED_PRODUCTS: Product[] = [
    {
        id: 101,
        name: 'Dark Magician',
        description: 'O mago supremo em termos de ataque e defesa.',
        price: 89.9,
        image: '/images/cards/detail/related-1.png',
        game: 'yugioh',
        cardType: 'MONSTER',
        rarity: 'Ultra Rare',
        cardSubtypes: 'Spellcaster',
        stock: 12,
        badge: 'NOVO',
    },
    {
        id: 102,
        name: 'Red-Eyes Black Dragon',
        description: 'Um dragão feroz com um ataque mortal.',
        price: 210.0,
        oldPrice: 250.0,
        image: '/images/cards/detail/related-2.png',
        game: 'yugioh',
        cardType: 'MONSTER',
        rarity: 'Secret Rare',
        cardSubtypes: 'Dragon',
        stock: 5,
        badge: 'PROMO',
    },
    {
        id: 103,
        name: 'Stardust Dragon',
        description: 'Dragão synchro que protege suas cartas da destruição.',
        price: 450.0,
        image: '/images/cards/detail/related-3.png',
        game: 'yugioh',
        cardType: 'MONSTER',
        rarity: 'Ghost Rare',
        cardSubtypes: 'Synchro',
        stock: 2,
    },
    {
        id: 104,
        name: 'Exodia the Forbidden',
        description: 'Uma das cinco peças que garantem a vitória automática.',
        price: 120.0,
        image: '/images/cards/detail/related-4.png',
        game: 'yugioh',
        cardType: 'MONSTER',
        rarity: 'Ultra Rare',
        cardSubtypes: 'Spellcaster',
        stock: 3,
    },
];
