import { FilterType, Product } from './types';

export const FILTER_OPTIONS: { label: FilterType; cardType: string | null }[] = [
    { label: 'TODOS', cardType: null },
    { label: 'MONSTROS', cardType: 'MONSTER' },
    { label: 'MAGIAS', cardType: 'SPELL' },
    { label: 'ARMADILHAS', cardType: 'TRAP' },
    { label: 'TERRENOS', cardType: 'LAND' },
    { label: 'CRIATURAS', cardType: 'CREATURE' },
];

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 1,
        name: 'The Wandering Emperor',
        description: 'Planeswalker lendária de Magic: The Gathering.',
        price: 89.9,
        image: '/images/cards/miniatures/the-wandering-emperor.jpg',
        fullImage: '/images/cards/full/the-wandering-emperor.jpg',
        game: 'mtg',
        cardType: 'CREATURE',
        rarity: 'Mythic Rare',
        stock: 4,
        badge: 'NOVO',
    },
    {
        id: 2,
        name: 'Gift of Orzhova',
        description: 'Encantamento clássico do clã Orzhov.',
        price: 12.5,
        oldPrice: 25.0,
        image: '/images/cards/miniatures/gift-of-orzhova.jpg',
        fullImage: '/images/cards/full/gift-of-orzhova.jpg',
        game: 'mtg',
        cardType: 'SPELL',
        rarity: 'Uncommon',
        stock: 15,
        badge: 'PROMO',
    },
    {
        id: 3,
        name: 'Poe',
        description: 'Carta ilustrada com arte exclusiva.',
        price: 45.0,
        image: '/images/cards/miniatures/poe.jpg',
        fullImage: '/images/cards/full/poe.jpg',
        game: 'mtg',
        cardType: 'CREATURE',
        rarity: 'Rare',
        stock: 7,
    },
    {
        id: 4,
        name: 'Sword of Feast and Famine',
        description: 'Artefato poderoso de equipamento.',
        price: 120.0,
        image: '/images/cards/miniatures/sword-of-feast.jpg',
        fullImage: '/images/cards/full/sword-of-feast.jpg',
        game: 'mtg',
        cardType: 'TRAP',
        rarity: 'Mythic Rare',
        stock: 3,
    },
];
